### ISSUE TITLE
Enter button at firefox

### ISSUE THREAD

**Issue by kofdasad** [andersonba/yve-bot#195]
Hi!

if you press "enter" after a String type message, instead of using the "send" button...
this reload the page, and cut the chat off

do you know about this?

even at example pages or playgrouds it happens.

thank you

**Comment by andersonba** [comment]
Hi!

I can't reproduce this problem here.
What's your browser or device?

**Comment by kofdasad** [comment]
Thank you for your quick response...

for example at:

https://andersonba.github.io/yve-bot/

the bot ask "What's your name?"

you can type you name...
 id you press "Enter" button at your keyboard, it refreshes the page instead of following the chat.
 
 it only happens at Firefox('m using 85.0 ver(64-Bits)) on PC
 
 i tried it at some older versions(80.0+), and still doesn't work
 
 Works perfectly at Chrome and Edge

**Comment by andersonba** [comment]
So, I tested on Firefox and you're right, it was really broken. Nice catch!
I just uploaded version 1.20.2 with the fix.

Thank you!
