### ISSUE TITLE
Full log at console

### ISSUE THREAD

**Issue by kofdasad** [andersonba/yve-bot#197]
Hi!

i'm testing and saving log(record everything that happen), but for example it doesn't show the executed actions...
For example at https://andersonba.github.io/yve-bot/ you can end it with the playground redirect, but to log this is transparent:

![image](https://user-images.githubusercontent.com/7155029/106947846-f0a1f300-66f8-11eb-85be-3677457c650c.png)

there is a way to "activate" a full logging?
not only show the user input...

thank you

**Comment by andersonba** [comment]
Did you try to [bindings events](https://andersonba.github.io/yve-bot/docs/api-core.html#binding-events)?
