### ISSUE TITLE
how to pass data using session?

### ISSUE THREAD

**Issue by yasinAtlibra** [andersonba/yve-bot#36]
How can I pass data through session?

For example,

               bot.session(channelId,{ somedata }).hear(text);

Then, how can I get it in "talk event"

            bot.on("talk", (text, data, sid) => {

              //how to get "somedata" here?

           })

I logged these "data" and could not figure out how to get "somedata"?

Thanks in advance!

**Comment by andersonba** [comment]
Do you mean user context?
https://github.com/andersonba/yve-bot/issues/37
It will be available in next version.
