### ISSUE TITLE
using session?

### ISSUE THREAD

**Issue by yasinAtlibra** [andersonba/yve-bot#43]
One question about using session. I am doing as follows.

I starting both as 

                      bot.session(sid).start();

and i save the bot state as following

                      bot.on("storechanged",(state,sid)=>{
                         save_to_database({state,sid})
                     })

and I pass the state as following
 
                    const state = read_from_database(sid)
                    bot.session(sid,{state}).hear(message);

am I using doing correct?  because i am having problem at the previous line, the bot is not responding.
The state is look like this 

                    { currentIdx: 0, waitingForAnswer: true, output: {} } 

Want to know if this is correct way of using yve-bot.
Thanks in advance!

**Comment by rafaelverger** [comment]
@yasinAtlibra I think u're using the `storeChanged` handler and the `session` method wrongly.. the handler for `storeChanged` receives the actual store's state, not the "bot's state" and `session` method needs two parameters: `sid` and `options`. You can pass a new store data inside options param.. check the code below:
```js
bot.on("storechanged",(store)=>{
  save_to_database({store, sid: bot.sessionId})
});

function initBotFromDB(bot) {
  const storeFromDB = read_from_database(bot.sessionId);
  bot.session(bot.sessionId, { store: storeFromDB });
}
```

**Comment by andersonba** [comment]
Thanks, @rafaelverger!
Remember to use `storeChanged` instead of `storechanged` event name.

**Comment by andersonba** [comment]
@yasinAtlibra did you check [socket.io](https://github.com/andersonba/yve-bot/tree/master/examples/socket.io) example?

**Comment by yasinAtlibra** [comment]
@rafaelverger I was following  socket.io example, and what I did is exactly the same as in the example. 
I think the basic idea is save  the store to database when "storeChanged" is invoked, and load the store from database and use it in "hear" method. am I right?

I did not understand your "initBotFromDB" method. I am currently doing,
    
           bot.session(sid).start(); 

and how do you use "hear" ?

**Comment by yasinAtlibra** [comment]
@andersonba Yes, I checked socket.io example and was following it.

**Comment by yasinAtlibra** [comment]
@andersonba @rafaelverger I made it. My strategy is correct (following the example mentioned). thanks guys :)
