### ISSUE TITLE
Add replyMessage as prop options from SingleOptions field

### ISSUE THREAD

**Issue by rafaelverger** [andersonba/yve-bot#66]
It must be possible to set different replyMessages for each options from a SingleOption field. It should also be possible to do so for MutipleOptions field but for them is not as simple as to the first one mentioned

**Comment by andersonba** [comment]
Really nice!

**Comment by andersonba** [comment]
Available in next release 🎉 

For `MultipleOption` type, it gets the first item with replyMessage defined.
